### ISSUE TITLE
Live demo broken

### ISSUE THREAD

**Issue by twilco** [RealScout/avr-emulator#6]
Clicking "Run" or "Step" doesn't appear to do anything - I'm assuming that's not the intention :).  Some console errors, too:

```
Uncaught DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.
    at http://realscout.github.io/avr-emulator/bundle.js:22588:38
    at http://realscout.github.io/avr-emulator/bundle.js:21577:75
    at dispatch (http://realscout.github.io/avr-emulator/bundle.js:617:74)
    at http://realscout.github.io/avr-emulator/bundle.js:22416:8
bundle.js:22444 WebSocket connection to 'ws://72.2.118.178:8000/' failed: Connection closed before receiving a handshake response
(anonymous) @ bundle.js:22444
17bundle.js:22588 WebSocket is already in CLOSING or CLOSED state.
(anonymous) @ bundle.js:22588
134bundle.js:22588 WebSocket is already in CLOSING or CLOSED state.
```

**Comment by MichaelAP** [comment]
Hey @twilco. The person who built this repo is no longer with RealScout, and no longer wants to maintain the repo. I'm going to delete the repo next week, but feel free to fork it if you'd like. Thanks for your interest!

**Comment by twilco** [comment]
Thanks for the heads up @MichaelAP!
